# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7408dae98e10f2cf5665aa8df6c73b291dd8222034e4bebbf61a63ecea7e2015a00cf9914c9d2f2af1180dfdd063bb7f462c558a8e2dd3dc30506fa84e62021

test:
  secret_key_base: 2f8727178ab0c0d2e17f2794eb31bee65ed069563c98464c553d6fae0dd8e35438227094261cd48c9b3d481b0e303b7f4781c947f2927965d2d3670b90a4fcf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
